- .github/workflows/ci.yaml
- README.md
Fix CI errors caused by attempting to use poetry 3.8 for all versions of python
> cache poetry by python version

- poetry.lock
- pyproject.toml
Make `snowflake-sqlachemy` a core dependency to provide our users a golden path for working with snowflake out of the box.
Also update min gx version
> Add `snowflake-sqlalchemy` as core dependency

- .github/workflows/ci.yaml
- great_expectations_cloud/agent/Dockerfile
- tasks.py
not trivial fix to add support for arm64
I removed platform tag in previous [PR]( https://github.com/great-expectations/cloud/pull/18/files#diff-06925c091c7ca7abfba230be53583ab49f0a56b5869b8e708681a8990d3bd3e6L1), which broke docker builds on apple silicon.
This reverts the change, but also reverts us back to emulating the agent on apple silicon.
> revert platform tag

- pyproject.toml
- tests/test_project.py
Due to dependency resolver issues, we should accept ANY version of GX (although >=17 is actually what is required). We can resolve the versioning issues in OSS later on
> [MAINTENANCE] Make `great_expectations` dependency unbounded

- great_expectations_cloud/agent/cli.py
- great_expectations_cloud/logging_cfg.py
- pyproject.toml
- tests/agent/test_cli.py
- tests/test_logging_cfg.py
Allow for more advanced configuration of the agent logger by passing the path to a json config file.
https://docs.python.org/3/library/logging.config.html#configuration-dictionary-schema
```console
$ gx-agent --help                                               
usage: gx-agent [-h] [--log-level LOG_LEVEL] [--log-cfg-file LOG_CFG_FILE]
optional arguments:
-h, --help            show this help message and exit
--log-level LOG_LEVEL
Level of logging to use. Defaults to WARNING.
--log-cfg-file LOG_CFG_FILE
Path to a logging configuration json file. Supercedes --log-level.
```
> Allow configuring logging from json file

- README.md
- poetry.lock
- pyproject.toml
- tasks.py
Add task for bumping the poetry/pypi version
- [Add `tomlkit` dev dependency ](https://tomlkit.readthedocs.io/en/latest/)for reading/writing from `.toml` files
- `tomli-w` does not  (as of now) preserve formatting or comments, so not a good choice for this task
```console
$ invoke version-bump --help
Usage: inv[oke] [--core-opts] version-bump [--options] [other tasks here ...]
Docstring:
Bump project version.
Options:
-p, --pre        Bump the pre-release version (Default)
-s, --standard   Bump the non pre-release micro version
```
> Add version bump developer `invoke` task

- poetry.lock
- pyproject.toml
Our Descriptive Metrics feature relies on `orjson`'s ability to serialize numpy types.
It should be a core dependency of the `great_expectations_cloud` package.
> Add `orjson` dependency to support Descriptive Metrics

- pyproject.toml
- tasks.py
Fix pre-release -> standard release logic.
The next release after a pre-release is a non-pre-release version.
```
0.0.1.dev1 -> 0.0.1 -> 0.0.2.dev0 -> 0.0.2dev1 -> 0.0.2
```
Followup to
- https://github.com/great-expectations/cloud/pull/41
The actual `0.0.3` release could be cut separately if desired.
> Release 0.0.3

- tasks.py
Simple invoke task for printing the local package version to the console.
Useful for getting the local version as part of the docker tagging step.
```console
$ invoke version     
0.0.6
```
> add `version`/`get-version` invoke task 

- .github/workflows/containerize-agent.yaml
- Add nightly trigger, so we pick up latest GX without requiring a merge into main
- Document a few steps
> enable nightly builds

- great_expectations_cloud/agent/message_service/asyncio_rabbit_mq_client.py
- pyproject.toml
Running agent in Docker will emit the following warning: 
```bash
DataContext is ready.
Opening connection to GX Cloud
WARNING:py.warnings:/app/great_expectations_cloud/agent/message_service/asyncio_rabbit_mq_client.py:228: DeprecationWarning: ssl.PROTOCOL_TLSv1_2 is deprecated
ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
GX-Agent is ready.
```
This PR updates the protocol to [`PROTOCOL_TLS_CLIENT`](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLS_CLIENT) which will auto-negotiate the highest protocol version between server and client.
> Update Deprecated SSL Protocol (`DeprecationWarning: ssl.PROTOCOL_TLSv1_2 is deprecated`)

- README.md
- examples/agent/cloudformation/README.md
- great_expectations_cloud/agent/agent.py
- tasks.py
- tests/agent/jobs/test_job_processing.py
Came across some instances where we were saying "agent" instead of "the GX Agent". Updated these and also updated some style/grammar along the way to better adhere to the styleguide
> Standardize naming/style/grammar in READMEs and comments

- .github/workflows/containerize-agent.yaml
Ensure that the version on [docker hub](https://hub.docker.com/r/greatexpectations/agent) matches the pypi version (specified in pyproject.toml). This is done by pulling the pyproject.toml version in when pushing to docker hub and using it as one of the tags (along with `latest`).
Tested here: https://github.com/great-expectations/cloud/actions/runs/7227829270/job/19696191300
See also source ticket: https://greatexpectations.atlassian.net/browse/ZEL-235
> [MAINTENANCE] Update tagging strategy

- .github/workflows/containerize-agent.yaml
Removing so we don't overwrite the agent build nightly.
> [MAINTENANCE] Remove schedule for containerizing the agent

- poetry.lock
- pyproject.toml
Critically, this version includes changes to the default value for the `SQLDatasource.create_temp_table` field from `True` to `False` and a related fix for `QueryAsset` so that it works without `temp_tables`.
> Bump Docker GX OSS version to `0.18.6`

- README.md
- poetry.lock
- pyproject.toml
Bump Docker GX OSS version to `0.18.7`
Update README
Added instructions for updating Dockerfile dependencies (the `poetry.lock` file)
> Bump Docker GX OSS version to `0.18.7`

- .github/workflows/ci.yaml
The filter was not catching changes in https://github.com/great-expectations/cloud/pull/91. These changes make sure we are checking all subfolders for changed files.
See failing then passing test after version bump in https://github.com/great-expectations/cloud/pull/91 to verify this is working:
> Fix filter for check if agent changed

- .github/workflows/ci.yaml
- great_expectations_cloud/agent/actions/run_column_descriptive_metrics_action.py
- pyproject.toml
- tests/agent/actions/test_run_column_descriptive_metrics_action.py
Test that we can connect to the datasource before running CDM. The `datasource.test_connection()` method raises a human readable warning that will be visible in the agent logs.
Demo: https://us02web.zoom.us/clips/share/EMmyDoL7rscoKeGl8ZuA0gNtiy3tatwrWslCejOBP296l4dqAI6VSowtROnL1oUtvhK55Ii7MRmgOrAdjbYJ5-Mf.8w-XnYgbkmOcQKtK
> Test connection before running CDM

- great_expectations_cloud/agent/agent.py
- great_expectations_cloud/agent/constants.py
- poetry.lock
- pyproject.toml
- tests/agent/conftest.py
- tests/agent/test_agent.py
Ensure that a `User-Agent: gx-agent/<AGENT_VERSION>` header is always set when making calls to the GX Cloud REST API.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent
Doing this so that we can differentiate between API calls coming from the `gx-agent` vs standard `great_expectations`.
In the context of a job, the `Agent-Job-Id` header is also set on every API request.
The header details are controlled in `great_expectations.core.http` by non-public methods so I had to monkeypatch one of these methods to ensure the header is properly set.
For the V1 release, we should expose a public method of doing this operation, and then this implementation can be changed. I will implement this in a followup so as not to force a new `0.18.x` release.
> Set `User-Agent: gx-agent`& `Agent-Job-Id` on GX Cloud API requests 

- LICENSE
Update terminology to match product glossary - text document was provided in this thread: https://greatexpectationslabs.slack.com/archives/C05R8RE43CL/p1705598882375079?thread_ts=1701803742.800279&cid=C05R8RE43CL
> Update LICENSE to use "GX Agent" instead of "GX Cloud Agent"

- great_expectations_cloud/agent/agent.py
- pyproject.toml
Talked to @Kilo59 about the comment [here](https://github.com/great-expectations/cloud/pull/95#discussion_r1457834597). We decided it would be helpful to surface the version of GX being used by the agent here so that users who don't use the Docker image can easily see which version of GX is being used.
Example startup printout with this change:
> F/zel 276/surface gx version in agent startup

- great_expectations_cloud/agent/agent.py
- pyproject.toml
Prior to this change, users noted some confusion about the error message used in the GX Agent printout, since sometimes this error message happens when a job is completed with errors (as opposed to when a job fails to complete), like when testing Data Source config.
For that reason I updated the error message to indicate that the job completed with errors. Future enhancements could add a more-specific message, but this should be fine for now.
Before change:
After change:
> update agent printout error message for clarity

- poetry.lock
- pyproject.toml
Adding the `psycopg2` package as an optional dependency
https://www.psycopg.org/docs/install.html#psycopg-vs-psycopg-binary
Can be installed using the `postgres` extra
```
pip install 'great_expectations[postgres]'
```
Or with poetry
```
poetry install --with sql
```
> Add `pyscopg2` as optional dependency

- .github/dependabot.yml
Use `pip` instead of `poetry` to set the package ecosystem for `poetry`.
See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem (table and tip below table).
"Tip: For package managers such as pipenv and poetry, you need to use the pip YAML value. For example, if you use poetry to manage your Python dependencies and want Dependabot to monitor your dependency manifest file for new versions, use package-ecosystem: "pip" in your dependabot.yml file."
> Update dependabot versioning settings

- Dockerfile
- README.md
- pyproject.toml
Adds `yellow_tripdata.db` (7MB) sqlite database to the docker image.
This ensures that every agent has access to some data they can connect to explore and run agent-powered interactions from the cloud.
> Add `yellow_tripdata.db` to Docker Image

- great_expectations_cloud/agent/agent.py
- pyproject.toml
- tests/agent/conftest.py
- tests/agent/test_agent.py
The `AgentJobId` header was not being set for the `RunCheckpointEvent`/`RunCheckpointAction` but is for other events like `DraftDatasourceConfigEvent `
- Initial implementation https://github.com/great-expectations/cloud/pull/97
This will ensure that `Agent-Job-Id` is set for any GX Cloud API call that originates from core OSS code.
`_set_http_session_headers()` is modifying global state (it's monkeypatching a method in the OSS code), and can be called with or without a `correlation_id`.
https://github.com/great-expectations/cloud/blob/a3fee2fbcd5c041a66ebbfbf3e545450cc49ed6c/great_expectations_cloud/agent/agent.py#L166-L167
~My initial guess was that `_set_http_session_headers()` was being called without the `correlation_id` and this was causing the `Agent-Job-Id` to be unset, but after …
> Fix missing `Agent-Job-Id` for `CheckpointRun` events 

- README.md
- poetry.lock
- pyproject.toml
- tasks.py
The source install of `pyscopg2` is not working for our docker image and requires some additional work to fix.
Reverting to using `pyscopg2-binary` as this seems to work without issues. Comments from one of the `pyscopg2` developers suggest that using this for our agent won't actually be a problem as our agent will only be connecting to postgres in a single thread.
>The use of the -binary packages in production is discouraged because in the past they proved unreliable in multithread environments. This might have been fixed in more recent versions but I have never managed to reproduce the failure.
- https://github.com/great-expectations/cloud/pull/101
- https://www.psycopg.org/docs/install.html#psycopg-vs-psycopg-binary
- https://github.com/psycopg/psycopg2/issues/1283#issuecomment-85033303 …
> Bugfix - `No module named 'psycopg2'`

- Dockerfile
fix release failure: remove redundant command
CMD failing when in docker compose
Verified fix locally as:
- docker run
- docker compose
> fix release failure: remove redundant command

- great_expectations_cloud/agent/actions/draft_datasource_config_action.py
- great_expectations_cloud/agent/agent.py
- great_expectations_cloud/agent/event_handler.py
- great_expectations_cloud/agent/message_service/asyncio_rabbit_mq_client.py
- great_expectations_cloud/agent/message_service/subscriber.py
- great_expectations_cloud/agent/models.py
- pyproject.toml
- tasks.py
- tests/agent/actions/test_draft_datasource_config.py
- tests/agent/conftest.py
- tests/test_project.py
Require that generics specify a type.
This is part of the default `mypy` `strict` mode.
https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-disallow-any-generics
```
x: list # this is no longer allowed
x: list[str] # allowed
x: list[typing.Any] # also allowed but should generally be discouraged
x: typing.List[str] # required for pydantic models that use annotations at runtime
```
> Stricter Generics Typing

- great_expectations_cloud/agent/models.py
- pyproject.toml
In #127, we are adding a property to an existing Event model. This change will be merged to both `mercury` and `cloud`, but we currently don't allow for extra properties on event models...so if #127 is merged and users do not immediately upgrade their GX Agent version, the RunCheckpointEvent type is not recognized and therefore cannot be processed, which breaks running checkpoints/validations.
To ensure backwards compatibility, we need to make sure that the Agent code can recognize events even if they have additional properties; hence this change.
I'm open to doing this another way if there are suggestions.
> Update event models to allow extra properties to ensure backwards compatibility

- .pre-commit-config.yaml
- great_expectations_cloud/agent/agent.py
- poetry.lock
- pyproject.toml
Turn on `ruff` `ASYNC` rules
https://docs.astral.sh/ruff/rules/#flake8-async-async
Update `ruff` `0.2.1` -> `0.2.2`
Fix a potential problem with the `redeliver_message` task being garbage collected.
> flake8-async linting

- poetry.lock
- pyproject.toml
Update the version of GX used in the Agent to the latest release, 0.18.10
Created by running:
`poetry update great_expectations`
`invoke version-bump --standard`
> Update gx version to 0.18.10

- great_expectations_cloud/agent/actions/run_column_descriptive_metrics_action.py
- great_expectations_cloud/agent/event_handler.py
- pyproject.toml
Refactor the CDM action to match the signature of the parent action (context-only init). Provide defaults for the existing params.
Dev release since this is only a refactor that does not change functionality.
Thanks @billdirks for the catch!
> Refactor CDM action

- great_expectations_cloud/agent/actions/run_column_descriptive_metrics_action.py
- pyproject.toml
Issue:
Running CDM was returning `'ColumnDescriptiveMetricsMetricRetriever' object is not iterable` error after changes in #149 
Solution:
The BatchInspector constructor expects a list of `MetricRetriever` - pass in a list instead
> ZEL-535: Fix CDM error - pass metrics retriever as a list to avoid iterable error

- .github/workflows/ci.yaml
- .github/workflows/containerize-agent.yaml
- codecov.yml
- tests/test_project.py
Add `codecov.yml` file to take advantage of additional `flag` features.
>Here are just a few features unlocked by adding Flag definitions to your YAML.
1. Flags in [PR Comments](https://docs.codecov.com/docs/pull-request-comments) and [Status Checks](https://docs.codecov.com/docs/commit-status) in your Github, Gitlab, Bitbucket instance
2. Overlay [source code coverage in UI](https://docs.codecov.com/docs/viewing-source-code) by Flag
3. [Carryforward Flags](https://docs.codecov.com/docs/carryforward-flags) for partial test runs
Etc.
https://docs.codecov.com/docs/flags#step-2-flag-management-in-yaml
This is being used as part of an evaluation between coveralls + codecov
> Codecov flags config

- .github/workflows/ci.yaml
Make sure we bump the agent version via CI check when bumping dependencies e.g. GX version in `poetry.lock`.
> Force version bump on poetry.lock change

- .github/workflows/ci.yaml
- README.md
- poetry.lock
- pyproject.toml
Don't need both coveralls and codecov reports now that we have selected codecov as our coverage reporting tool.
> Remove coveralls

- .github/workflows/containerize-agent.yaml
Add `stable` tag to agent image that is pushed to dockerhub.
(Note: we are keeping the `latest` tag for now.)
> Z2-296: Add stable tag to dockerhub

- .github/workflows/ci.yaml
`invoke` needs to be run from within the virtual env.
What we should probably do is update our CI usage of poetry to not use a virtual env and install packages directly to the runner env.
> Fix `invoke pre-release` ci step

- .github/dependabot.yml
Updating dependabot to run daily instead of weekly as discussed here: https://greatexpectationslabs.slack.com/archives/C05R8RE43CL/p1712930265826609
(Add'l changes for Z2-300 to come in a separate PR)
> Update dependabot to run daily instead of weekly

- .github/workflows/ci.yaml
- README.md
- pyproject.toml
- Only run the version bump related jobs if the `no version bump` label is not set.
- Update README with instructions.
Test runs of this functionality are in this PR (image below).
- [65bc60c](https://github.com/great-expectations/cloud/pull/243/commits/65bc60c2d0e694c6aee9284a99850bf4a5e30b34) bumped the version as expected (current functionality) after commit [fd29407](https://github.com/great-expectations/cloud/pull/243/commits/fd29407174e27c7a7e633308a00b4714aa697fc1) which changed `pyproject.toml`, a file tracked for changes that require version bump.
- After adding the `no version bump` label, version is not bumped in commit [90b1861](https://github.com/great-expectations/cloud/pull/243/commits/90b18610220d344e35191f9f8d2c33657f536d5c) - the version bump related jobs are skipped. …
> Add check-no-version-bump-label job

- Dockerfile
Remove build tools from final image, which addresses container vuln for python 3.11
Tests performed:
- build tools fail using base image python version
- psutil cannot be removed from dep chain
- upgrade python3-dev, failed
Conclusions:
- python3-dev: max version supported by our base image is [3.11.2](https://packages.debian.org/stable/python3-dev)
- psutil required indirectly by GX core
> remove build tools from Docker layer

- .github/workflows/ci.yaml
When we auto-bump the version in a dependabot PR, that stops dependabot from being able to automatically update the PR if a newer version of the dependency is released, e.g.:
Often dependabot PRs don't require a release ([instructions](https://github.com/great-expectations/cloud?tab=readme-ov-file#dependabot-and-releasespre-releases)), so this requires extra work to merge or close both the outdated dependabot PR and then the updated dependabot PR. Let's avoid by not auto-bumping the version on dependabot PRs using the tag dependabot uses itself to tag PRs: `dependencies`.
> Don't bump dependabot PRs with dependencies tag

- .github/workflows/ci.yaml
Fixes https://github.com/great-expectations/cloud/pull/287 where the conditional was placed on the wrong job.
> Move tag check to correct job

- great_expectations_cloud/agent/agent.py
- pyproject.toml
- Reverts great-expectations/cloud#220
Upcoming changes to `great_expectations` including `1.0` will introduce breaking changes where the version of great_expectations is of extra relevance.
The version of the GX Agent by itself has very little meaning to most users.
> Add back GreatExpectations version log at Agent startup

- pyproject.toml
* No GX Core version update needed (there hasn't been a release in the past week)
* Didn't merge the dependabot PRs since pod Zelda is in an offsite
* Also we've been seeing some CI failures ([example](https://github.com/great-expectations/cloud/actions/runs/9407873378/job/26096782878?pr=292)) on some of those PRs; wondering if we will see them here, too... (update: no issues with this PR)
> invoke release

- pyproject.toml
* All dependabot PRs have been merged
* GX Core version in pyproject is up to date; no changes needed
* Changes in this PR are the result of running `invoke release`
> update release version

- great_expectations_cloud/agent/models.py
- pyproject.toml
- tests/agent/test_event_handler.py
* Followed pattern described [here](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.extra). 
```python
from pydantic import BaseModel, ConfigDict
class User(BaseModel):
model_config = ConfigDict(extra='ignore')  
name: str
``` 
* Model also defaults to `ignore` for extra fields, but there may be value in making this explicit
> Update Pydantic Model - Ignore Extra fields for `EventBase` only

- poetry.lock
- pyproject.toml
In preparation for the `snowflake-sqlalchemy` `1.6.0` release that will un-pin `sqlalchemy` 1. 
We need to ensure we don't accidentally move the agent to Snowflake SQLAlchemy 2 without testing it first. 
https://github.com/snowflakedb/snowflake-sqlalchemy/releases/tag/v1.6.0
> Pin SQLAlchemy 1

- pyproject.toml
Enable the `possible-undefined` optional mypy rule.
>## Warn about variables that are defined only in some execution paths
>
>mypy generates an error if it cannot verify that a variable will be defined in all execution >paths. This includes situations when a variable definition appears in a loop, in a >conditional branch, in an except handler, etc. For example:
```python
from typing import Iterable
def test(values: Iterable[int], flag: bool) -> None:
if flag:
a = 1
z = a + 1  # Error: Name "a" may be undefined [possibly-undefined]
for v in values:
b = v
z = b + 1  # Error: Name "b" may be undefined [possibly-undefined]
```
https://mypy.readthedocs.io/en/stable/error_code_list2.html#warn-about-variables-that-are-defined-only-in-some-execution-paths-possibly-undefined
- …
> mypy - enable `possibly-undefined`

- great_expectations_cloud/agent/agent.py
- great_expectations_cloud/agent/models.py
- poetry.lock
- pyproject.toml
- tests/agent/actions/checkpoints/test_run_checkpoint_action.py
- tests/agent/actions/data_assistants/test_run_missingness_data_assistant_action_utils.py
- tests/agent/actions/data_assistants/test_run_onboarding_data_assistant_action.py
- tests/agent/actions/test_draft_datasource_config.py
- tests/agent/actions/test_list_table_names_action.py
- tests/agent/actions/test_run_metrics_list_action.py
- tests/agent/test_agent.py
- tests/agent/test_event_handler.py
- tests/integration/actions/test_checkpoint_action.py
- tests/integration/actions/test_draft_datasource_config_action.py
- tests/integration/actions/test_metric_list_action.py
Pass the org id to the GX Runner via the event by adding to all of the event models. The org id is needed by the runner to pull the correct context configuration related to the org before running the selected action. [Demo Video](https://us02web.zoom.us/clips/share/eA0CfUsBJhTt2KsQ1T3S70Mu4x2ixSpNVkmZmCjgqLGASFskk6ENTuXo32olPeFlOfY8QeYnluXy84ObQ8qu42EY.SA8Y2kDXARYFW95c)
See also https://github.com/greatexpectationslabs/mercury/pull/3514 for the related backend change which should merge first.
> Add org id to event models

- great_expectations_cloud/agent/models.py
- pyproject.toml
Make org ID optional until we can backfill org_id on existing schedules. See also: https://greatexpectationslabs.slack.com/archives/C05R8RE43CL/p1720642064478209 and https://github.com/greatexpectationslabs/mercury/pull/3524
> Make org ID optional on events

- great_expectations_cloud/agent/agent.py
- pyproject.toml
Updating Handle-Event workflow in Agent.
* No behavior is changed, just a helper method is added, and `_handle_event` takes in one additional parameter (`data_context`),  which is then passed to the `EventHandler` rather than `self._data_context` directly. 
* Why is this needed? 
* GX-Runner inherits from GX-Agent, and requires a DataContext to be retrieved per-event. 
* This means are able to override the `_get_data_context()` method in the runner repo and keep the event handling behavior consistent between GX-Agent and GX-runner. 
* [PR in GX-runner that enables it to retrieve a DataContext per event](https://github.com/greatexpectationslabs/gx-runner/pull/58)
> Refactor HandleEvent workflow to take in DataContext as parameter

- great_expectations_cloud/agent/agent.py
- pyproject.toml
The runner needs to retrieve these values differently. Adding two small methods we can override in the runner to keep the code consistent. We can diverge later if needed.
> Use overridable methods for org ID and auth token

- great_expectations_cloud/agent/agent.py
- pyproject.toml
Followup to https://github.com/great-expectations/cloud/pull/349 to pass the event context for retrieval of the organization ID in the runner.
> Pass event context

- great_expectations_cloud/agent/actions/agent_action.py
- great_expectations_cloud/agent/actions/data_assistants/run_missingness_data_assistant.py
- great_expectations_cloud/agent/actions/data_assistants/run_onboarding_data_assistant.py
- great_expectations_cloud/agent/actions/draft_datasource_config_action.py
- great_expectations_cloud/agent/actions/list_table_names.py
- great_expectations_cloud/agent/actions/run_metric_list_action.py
- great_expectations_cloud/agent/agent.py
- great_expectations_cloud/agent/event_handler.py
- pyproject.toml
- tests/agent/actions/checkpoints/test_run_checkpoint_action.py
- tests/agent/actions/data_assistants/test_run_missingness_data_assistant_action_utils.py
- tests/agent/actions/data_assistants/test_run_onboarding_data_assistant_action.py
- tests/agent/actions/test_draft_datasource_config.py
- tests/agent/actions/test_list_table_names_action.py
- tests/agent/actions/test_run_metrics_list_action.py
- tests/agent/actions/test_unknown.py
- tests/agent/test_event_handler.py
- tests/integration/actions/test_checkpoint_action.py
- tests/integration/actions/test_draft_datasource_config_action.py
- tests/integration/actions/test_metric_list_action.py
Pass in information to each action that is needed to make calls back to cloud. Formerly these were retrieved from env vars but these need to be retrieved differently in the runner vs the agent so are abstracted out into the previously added functions `get_organization_id`, `get_data_context` and base URL is still retrieved from env var.
> Pass in base_url, org ID and auth key to each action

- README.md
- great_expectations_cloud/agent/agent.py
- pyproject.toml
This standardizes a couple things around `organization_id`. Chiefly:
- It's now passed as part of the `extra` payload for each call to `LOGGER`, rather than just the errors.
- It's no longer passed as an internal function argument, instead defaulting to pulling the value from the class properties.
- It shortens the variable names from `organization_id` to `org_id` because it's more concise.
It also removes unused `event_context` parameters from the function signatures of `get_data_context` and `get_organization_id`.
As we're building out additional features around connecting to and automating connections to data sources, we'll need to increase and standardize visibility into the intended actions and their originating organizations.
> add org_id to log payload & cleanup

- great_expectations_cloud/logging/logging_cfg.py
- pyproject.toml
The following log uses fstrings:
```
logger.error(
"Snowflake Connector for Python Version: %s, "
"Python Version: %s, Platform: %s",
SNOWFLAKE_CONNECTOR_VERSION,
PYTHON_VERSION,
PLATFORM,
)
```
and was causing 50 raw logs per execution.
Updated, show args uninterpolated, added TODO for uncommon case
```
{"args": ["3.12.0", "3.10.14", "Linux-5.10.220-209.869.amzn2.x86_64-x86_64-with-glibc2.36"], "levelname": "ERROR", "filename": "cli.py", "module": "cli", "exc_info": null, "stack_info": null, "funcName": "main", "created": 1723489949.485179, "relativeCreated": 2257.412910461426, "event": "Snowflake Connector for Python Version: %s, Python Version: %s, Platform: %s", "level": "ERROR", "logger": "root", "timestamp": "2024-08-12T19:12:29.485179+00:00"}
```
> remove modification of logging args

- .github/workflows/ci.yaml
- tests/test_project.py
Prevent getting rate limited by the pypi API.
Running this test involves hitting the `pypi` API for version information. When we run it for every version of Python in parallel, we can occasionally hit the rate limit and fail the CI.
This change skips this test for every minor version of python except the one declared in the `.python-version` file.
> Prevent `pypi` rate-limiting in tests.

- pyproject.toml
- tests/agent/test_agent.py
`test_gx_agent_invalid_token` was failing because it was actually making an API call instead of failing first.
Since we don't validate the content of the `GX_CLOUD_ACCESS_TOKEN` in Core or the agent/runner then anything we use for the token value would not fail until we try to actually call the backend.
This test now checks that an error is raised if no access token is provided, which fails as expected (with a different exception). I also thought about removing this test but I think there is value in ensuring that we fail if no token is provided.
> [MAINTENANCE] Fix failing test

- Dockerfile
Removes the `gcc-12`, `cpp-12`, and `cpp` from the image after build steps complete. These are unneeded and `gcc-12` is getting flagged by vulnerability scans.
> Remove unneeded build-time packages gcc and cpp

- tests/integration/actions/conftest.py
- tests/integration/actions/test_checkpoint_action.py
- tests/integration/actions/test_list_table_names.py
- tests/integration/actions/test_run_scheduled_checkpoint.py
- tests/integration/actions/test_run_window_checkpoint.py
A few agent `Actions` were missing integration tests, and this PR adds them. For ones that use common fixtures, they were moved to a shared `conftest.py` file. 
* `ListTableNamesAction`
* `RunScheduledCheckpointAction`
* `RunWindowCheckpointAction` (just a stub was added)
> Agent Integration tests - missing tests

- poetry.lock
- pyproject.toml
- Bumping GX Core to 1.1.1
- Doing so drops 3.8 support, so had to match in this project
> v1 unit tests, bump gx to 1.1.1

- README.md
- great_expectations_cloud/agent/agent.py
- pyproject.toml
Update logging in Agent so that we are long passing `Event` object directly into logs. This will make debugging much easier.
> Logging - Event obj is not used directly

- great_expectations_cloud/agent/agent.py
- pyproject.toml
- tests/agent/actions/test_draft_datasource_config.py
- tests/agent/test_agent.py
In the Agent we are using `correlation_id` and `job_id` interchangeably, which can cause confusion. This PR intends to use `correlation_id` in all locations, since it is what is used by mercury.
> Refactor to ensure more consistent usage of correlation_id

- great_expectations_cloud/agent/agent.py
- pyproject.toml
- adds agent headers to remaining stores (Data Source and Asset)
- overrides GX Core user agent for all stores
Requests coming from GX Agent should have GX Agent user agent, otherwise, they're not distinguishable from notebook or script usage
> Add headers to all stores

- great_expectations_cloud/agent/message_service/asyncio_rabbit_mq_client.py
- pyproject.toml
Some exception types do not have a `reply_code` or `reply_text`. Before logging, we check the exception type.
> Log only if certain type of error is found

- great_expectations_cloud/agent/agent.py
- great_expectations_cloud/agent/config.py
- pyproject.toml
- tests/agent/test_agent.py
Move the configuration of the progress bar from the GX Runner to the Agent, where it will be controlled by an environment variable. This PR should be merged prior to removing config from the Runner. 
PR to remove progress bar config from the Runner is [here](https://github.com/greatexpectationslabs/gx-runner/pull/242).
Also see ticket [here](https://greatexpectations.atlassian.net/jira/software/c/projects/ZELDA/boards/85?selectedIssue=ZELDA-1124).
Added tests to check that we configure progress bars correctly when the agent is initialized, and also verified that this works locally when the `ENABLE_PROGRESS_BARS` environment variable is set to True, False, or when it is not set (defaults to True)
> Configure progress bars in the GX Agent 

- great_expectations_cloud/agent/agent.py
- pyproject.toml
- tests/agent/test_agent.py
Previously, the exception raised when either updating the job status or creating a job in the backend for scheduled jobs would show as a multi-line exception in datadog. Since these errors are raised during the processing of an action, they should be logged rather than raised. Other errors raised during the processing of an action are already successfully caught and logged.
This PR uses our existing json logging framework to log the error as json.
Example new log:
```
{"args": "()", "levelname": "'ERROR'", "filename": "'agent.py'", "module": "'agent'", "exc_info": "None", "stack_info": "None", "funcName": "'_log_http_error'", "created": "1732221296.059027", "relativeCreated": "11169.095039367676", "response": "<Response [204]>", "error_message": "'Status Update action had an error while …
```
> Capture exception via logs

- .github/workflows/ci.yaml
- .github/workflows/containerize-agent.yaml
- docker-compose.yml
- nginx.conf
- tasks.py
Add nginx to route mercury API calls to the correct port depending on whether or not we are hitting the v0 or v1 endpoint. This mirrors the pattern used in the `gx-runner` repo and will allow us to [re-enable integration tests](https://github.com/great-expectations/cloud/pull/549) for the Agent.
> Use nginx for routing mercury API calls 

- great_expectations_cloud/agent/models.py
- pyproject.toml
- tests/agent/actions/test_generate_schema_change_expectations_action.py
`GenerateSchemaChangeExpectationsEvent` does not need `ExpectationSuiteId` because it is generated per-asset when the Action is run.
> Schema Change Detection - Update Model, which does not need Suite ID

- great_expectations_cloud/agent/actions/generate_schema_change_expectations_action.py
- pyproject.toml
- tests/integration/actions/test_generate_schema_change_expectations.py
* Enable Integration test
* Added seed-data as part of the integration test that is subsequently cleaned up.
> GenerateSchemaChangeExpectationAction - Enable Integration Test

- great_expectations_cloud/agent/actions/generate_schema_change_expectations_action.py
- pyproject.toml
- tests/agent/actions/test_generate_schema_change_expectations_action.py
We need to surface errors if they occur while we are adding expectations for the schema detection DQ issue. Errors could occur for some, none or all assets. We want to be able to surface the number of errors, the number of attempted assets, and at least a summary of how many errors were encountered. 
Note: Currently the max number of error messages shown is 5, but this can be adjusted. Also the rendering is not showing line breaks, only spacing. We should consider addressing that but maybe in a follow up PR as this PR is already somewhat large and the action is not yet active.
> Improve error reporting for partial failed assets

- great_expectations_cloud/agent/actions/generate_schema_change_expectations_action.py
- pyproject.toml
- tests/agent/actions/test_generate_schema_change_expectations_action.py
Change the wording to match the designs. Remove the truncation. Followup from https://github.com/great-expectations/cloud/pull/564
Example message created using the code in this PR (working on the line breaks / formatting separately):
> Change wording in error message

- great_expectations_cloud/agent/actions/generate_schema_change_expectations_action.py
- pyproject.toml
Tiny change to use a bullet point instead of a dash.
Before:
After:
> Use bullet point in error to match design

- Dockerfile
Final piece for ZELDA-1124. This will disable progress bars on the agent by default, which is what we want for GX-managed agents.
> Disable progress bars in agent by default

- great_expectations_cloud/agent/actions/generate_schema_change_expectations_action.py
- tests/integration/actions/test_generate_schema_change_expectations.py
This test was failing because it could not connect to the backend at port 7000. Once we realized that both v0 and v1 are being served on port 5000 via this PR: https://github.com/great-expectations/cloud/commit/b84f86b7405b0b86bf63e2ea7986cb48eb674485, it meant that this test should also use port 5000. It also uses the common fixture instead of a test specific fixture.
> Reenable integration test

- great_expectations_cloud/agent/actions/generate_data_quality_check_expectations_action.py
- pyproject.toml
- tests/agent/actions/test_generate_data_quality_check_expectations_action.py
- tests/integration/actions/test_draft_datasource_config_action.py
- tests/integration/actions/test_list_table_names.py
* renaming an internal method to `_add_schema_change_expectation`  which will allow more autogenerated Expectations
> Rename `_add_data_quality_check_expectation` to be `_add_schema_change_expectation`, which is more accurate

- great_expectations_cloud/agent/agent.py
- pyproject.toml
* PR to allow for the Runner to set Correlation ID for Sentry Issues without too much code duplication.  That feature is enabled here - https://github.com/greatexpectationslabs/gx-runner/pull/286
* Adds call to `_set_sentry_tags()` method in `_handle_event` which is shared by both Agent and Runner, but in the Agent, this is a no-op.
> Allow GX-Runner to set Correlation ID for Sentry Issues

- great_expectations_cloud/agent/agent.py
- great_expectations_cloud/agent/config.py
- pyproject.toml
- tests/integration/actions/test_draft_datasource_config_action.py
- tests/integration/actions/test_list_table_names.py
When running on "bare metal" with the backend services running in docker, you can run
```sh
export GX_...=...
export AMQP_HOST_OVERRIDE=localhost
poetry run gx-agent
```
> Add ability to override the AMQP host and port

- .github/workflows/ci.yaml
- .github/workflows/containerize-agent.yaml
- .github/workflows/publish-to-pypi.yaml
- pyproject.toml
With poetry pinned and the caches invalidated, it looks like poetry 2.0.0 is working at least in the ci workflow. This PR upgrades poetry everywhere to 2.0.0, and after it merges if there is an issue with the pypi workflow we can downgrade there.
> Upgrade poetry in github workflows

- .github/workflows/publish-to-pypi.yaml
- pyproject.toml
Bump the python version since poetry 2.0.0 does not support python 3.8 any longer https://python-poetry.org/blog/announcing-poetry-2.0.0#changed
> Publish to pypi python upgrade

- great_expectations_cloud/agent/agent.py
- great_expectations_cloud/agent/message_service/asyncio_rabbit_mq_client.py
- pyproject.toml
This PR addresses the scheduler issues discussed [here](https://greatexpectationslabs.slack.com/archives/C05R8RE43CL/p1736356433906939) by setting the RabbitMQ `prefetch_count` to 1 (since the GX Agent's `ThreadPoolExecutor` has a value of `max_threads=1`). This means that each worker can only hold one unacknowledged message at a time. More about the prefetch count [here](https://www.rabbitmq.com/docs/consumer-prefetch). 
Verified that this is working as expected locally. Without the prefetch count set, we see the warning logs when multiple validations are triggered manually from the UI: 
```
[INFO] great_expectations_cloud.agent.agent: The GX Agent is ready.
[DEBUG] great_expectations_cloud.agent.message_service.asyncio_rabbit_mq_client: Connection to RabbitMQ has been opened
[DEBUG] …
```
> Set RabbitMQ prefetch count to one

- great_expectations_cloud/agent/agent.py
- pyproject.toml
- tests/agent/test_agent.py
We thought we fixed this with ZEL-505 a long while back, but apparently we didn't. We're spewing TOOONS of logs about connection refused.
It appears that there are a few issues:
* We refresh creds after catching exceptions of a few types, but not the type that actually gets raised (subtle naming difference here). We now include the correct base type in our `except`. Pretty sure this was the actual reason things didn't get resolved.
* Even if we refreshed the creds, that happens before we wait to retry. This gap between getting creds and using them increases our chance of error. Note that this changes the flow around where we get/set `self._config` on the agent. _config is not optional, and anyplace that accesses it calls `self._get_config`.
* I added some jitter to the exponential backoff …
> Fix MQ Auth race condition

- great_expectations_cloud/agent/models.py
- pyproject.toml
- tests/agent/actions/test_generate_data_quality_check_expectations_action.py
- tests/integration/actions/test_generate_data_quality_check_expectations.py
Part of work for [Volume Change Detection](https://greatexpectations.atlassian.net/browse/GX-195). 
This PR adds `selected_data_quality_issues` to `GenerateDataQualityCheckExpectationsEvent`, and removes the unused `create_expectations` argument. 
Corresponding mercury PR [here](https://github.com/greatexpectationslabs/mercury/pull/4337).
> Add `selected_data_quality_issues` to `GenerateDataQualityCheckExpectationsEvent`

- great_expectations_cloud/agent/agent.py
- pyproject.toml
- tests/agent/test_agent.py
We already send these in request headers from the agent, but for consistency with other repos, we're also initializing our analytics with it.
> [MAINTENANCE] Pass user_agent_str to get_context

- great_expectations_cloud/agent/actions/generate_data_quality_check_expectations_action.py
- mise.toml
- pyproject.toml
- tests/agent/actions/test_generate_data_quality_check_expectations_action.py
Adding the additional `COLUMN_NULL_COUNT` and `TABLE_ROW_COUNT` metrics to the `_get_metrics` request resulted in unpredictable ordering of the metrics results, which caused the `_add_schema_change_expectation` function to fail more or less silently.
This PR accomplishes:
- adding the new metrics
- refactors `_add_schema_change_expectation` to be ordering agnostic
- adds logs to surface the underlying errors in autogenerated expectation failures
- adds test to cover the changes
> add table_row_count and column_null_count to fetched dqi metrics

- great_expectations_cloud/agent/__init__.py
- great_expectations_cloud/agent/utils.py
- pyproject.toml
- tests/agent/test_utils.py
Added a triangle interpolation helper that maps values based on how close they are to 50% sparse data. It takes values between 0-1 and outputs between 0-10, creating a triangle pattern (0→0, 0.5→10, 1→0) and rounds to the nearest 0.1. You can adjust the input/output ranges through a configurable options object.
* Function lives in `great_expectations_cloud/agent/utils.py` with a dataclass for configuration options
* Tests verify it works with default settings, custom ranges, different rounding precision, and edge cases
This will be useful for our upcoming completeness change detection work.
> [FEATURE]: Add triangular_interpolation utility function

- great_expectations_cloud/agent/actions/generate_data_quality_check_expectations_action.py
- pyproject.toml
- Adds a second window so that the expectation is +/- in cloud ui.
- Uses triangular interpolation result to determine expectation type
- Updates variable names for clarity.
> Windowed completeness expectations should be +/- offset

- Dockerfile
Updating in `pyproject.toml` was insufficient since `setuptools` lives outside the poetry enviornment.
> Update setuptools and poetry in dockerfile

- great_expectations_cloud/agent/agent.py
- pyproject.toml
Passing the context will allow us to set more useful tags in sentry
> Pass EventContext to methods setting sentry tags

- great_expectations_cloud/agent/actions/generate_data_quality_check_expectations_action.py
- pyproject.toml
This is a band aid solution so that we don't fail with [this](https://gx-cloud.sentry.io/issues/6509381994/?referrer=jira_integration) Sentry when a column is empty and a user wants to generate CCD expectations. We should figure out why the metric is being returned as `None` instead of `0`, but for now this will restore functionality to the UI.
> Temporary fix to handle CCD error when column is empty

- great_expectations_cloud/agent/actions/generate_data_quality_check_expectations_action.py
- pyproject.toml
- tests/agent/actions/test_generate_data_quality_check_expectations_action.py
Only add completeness change Expectations to columns that are missing coverage. 
This behavior is behind the `expect_non_null_proportion_enabled` feature flag.
> Only add completeness expectations to columns without coverage

- great_expectations_cloud/agent/__init__.py
- great_expectations_cloud/agent/actions/agent_action.py
- great_expectations_cloud/agent/event_handler.py
- great_expectations_cloud/agent/models.py
- pyproject.toml
- tests/agent/conftest.py
- tests/agent/test_event_handler.py
- Make `type[Event]` more broad by introducing `EventType`, which can be used during static analysis
- This enables us to define events in external systems without needing type ignores
> Add `EventType` for static analysis of dynamic `Event`s

- great_expectations_cloud/agent/event_handler.py
- great_expectations_cloud/agent/models.py
- pyproject.toml
This PR ensures that when we validate an Event against the union of available pydantic models, we're including any subclasses which may be defined by callers.
> use latest Event union state
