great-expectations/cloud

- .github/workflows/containerize-agent.yaml
- README.md
- great_expectations_cloud/agent/Dockerfile
- tasks.py
add containerize-agent workflow to github actions
> add containerize-agent workflow to github actions

- great_expectations_cloud/agent/actions/run_column_descriptive_metrics_action.py
Keep ColumnDescriptiveMetricsAction in sync with OSS changes in https://github.com/great-expectations/great_expectations/pull/8650
> [MAINTENANCE] Rename repository method

- .github/workflows/build.yaml
- .github/workflows/ci.yaml
- .github/workflows/publish-to-pypi.yaml
- pyproject.toml
setup build steps and publish to pypi
> setup build steps and publish to pypi

- .github/workflows/containerize-agent.yaml
add latest tag for the agent image
> add latest tag for the agent image

- great_expectations_cloud/agent/actions/data_assistants/run_missingness_data_assistant.py
- great_expectations_cloud/agent/actions/data_assistants/run_onboarding_data_assistant.py
- great_expectations_cloud/agent/actions/data_assistants/utils.py
- great_expectations_cloud/agent/agent.py
- great_expectations_cloud/agent/models.py
- tests/agent/actions/data_assistants/test_run_missingness_data_assistant_action_utils.py
- tests/agent/actions/data_assistants/test_run_onboarding_data_assistant_action.py
Account for recent changes made to OSS repo around agents before full cutover
> [MAINTENANCE] Migrate agent code 2023-09-28

- great_expectations_cloud/agent/actions/data_assistants/utils.py
- great_expectations_cloud/agent/actions/draft_datasource_config_action.py
- great_expectations_cloud/agent/actions/list_table_names.py
- pyproject.toml
- tests/agent/actions/data_assistants/test_run_onboarding_data_assistant_action.py
- tests/agent/actions/test_draft_datasource_config.py
Migrating code that was missed from prior migration (draft datasource)
> [MAINTENANCE] Migrate agent code 2023-09-29

- README.md
- poetry.lock
- pyproject.toml
Make `snowflake-sqlalchemy` an optional dependency
Define `great-expectations-cloud[snowflake]` extra
Add `pypi` badge
> Make snowflake-sqlalchemy an optional dependency

- .github/workflows/containerize-agent.yaml
add arm64 build platform for docker image
> add arm64 build platform for docker image

- great_expectations_cloud/agent/Dockerfile
change agent copy context for logging config
> change agent copy context for logging config

- great_expectations_cloud/agent/actions/agent_action.py
- great_expectations_cloud/agent/actions/data_assistants/run_missingness_data_assistant.py
- great_expectations_cloud/agent/actions/data_assistants/run_onboarding_data_assistant.py
- great_expectations_cloud/agent/actions/draft_datasource_config_action.py
- great_expectations_cloud/agent/agent.py
- great_expectations_cloud/agent/config.py
- great_expectations_cloud/agent/message_service/asyncio_rabbit_mq_client.py
- great_expectations_cloud/agent/message_service/subscriber.py
- great_expectations_cloud/agent/models.py
- great_expectations_cloud/agent/run.py
- great_expectations_cloud/logging_cfg.py
- pyproject.toml
- tasks.py
- tests/agent/message_service/amqp_errors.py
- tests/agent/message_service/test_rabbit_mq_client.py
- tests/agent/test_run.py
Enable the `mypy` `--strict` flag and fix new issues.
https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-strict
> Enable stricter typing rules

- poetry.lock
- pyproject.toml
https://astral.sh/blog/ruff-v0.1.0
> ruff `0.1.0`

- great_expectations_cloud/agent/agent.py
- great_expectations_cloud/agent/event_handler.py
- pyproject.toml
Add info level logs when handling events and updating status.
> Log event handling and status updates

- .gitignore
- LICENSE
- NOTICE
- pyproject.toml
Restore Apache 2.0 license and add copyright notice.
> Update license and add notice

- .pre-commit-config.yaml
- examples/agent/cloudformation/README.md
- examples/agent/cloudformation/agent-stack.yaml
- examples/agent/cloudformation/example-parameters.json
gx-agent cloudformation template
> gx-agent cloudformation template

- great_expectations_cloud/agent/message_service/asyncio_rabbit_mq_client.py
- pyproject.toml
> Rollback SSL Protocol change

- pyproject.toml
- Increment version to release to Pypi
> Increment version

- README.md
Forgot to actually link to our dockerhub page
> Fix Dockerbadge link

- poetry.lock
- pyproject.toml
Update to use `0.18.4` as a minimum.
Needed to support upcoming UI features.
> GX `0.18.4`

- pyproject.toml
`filterwarnings` now correctly filters warnings.
> `pyproject.toml` update - Warnings are Errors

- .github/dependabot.yml
Configure dependabot version updates. This will raise pull requests to keep our dependencies up to date.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#example-dependabotyml-file
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directory
This PR should not bump the agent version.
> Configure Dependabot Version Updates

- great_expectations_cloud/agent/actions/data_assistants/utils.py
- great_expectations_cloud/agent/actions/draft_datasource_config_action.py
- great_expectations_cloud/agent/actions/list_table_names.py
- pyproject.toml
- tests/agent/actions/data_assistants/test_run_onboarding_data_assistant_action.py
- tests/agent/actions/test_draft_datasource_config.py
- tests/agent/actions/test_list_table_names_action.py
Updates error message texts for consistency.
Changes to config error message text are related to #115.
> F/zel 389/update error message texts for consistency

- .github/workflows/dockerfile.yaml
- Dockerfile
Add CI job that smoketests container if Dockerfile changes
> add dockerfile ci check

- README.md
Add instructions to the readme for adding an action to the agent.
> Add instructions for adding an action

- .github/workflows/ci.yaml
- README.md
Comparing `codecov` with `coveralls`
This change does not introduce any new blocking ci steps
> Coverage with codecov

- .github/workflows/ci.yaml
- .github/workflows/dockerfile.yaml
- .pre-commit-config.yaml
- examples/agent/cloudformation/agent-stack.yaml
- examples/agent/kubernetes/deployment.yaml
Use prettier pre-commit hook for yaml formatting
> Prettier yaml formatting

- great_expectations_cloud/agent/actions/run_metric_list_action.py
- great_expectations_cloud/agent/models.py
- pyproject.toml
- tests/agent/actions/test_run_metrics_list_action.py
* Updating `RunMetricsEvent` to `RunMetricsListEvent`
* Update Event model to match what we are receiving from `mercury` BE
> Table Metrics - EventType rename

- great_expectations_cloud/agent/agent.py
- pyproject.toml
- tests/agent/test_agent.py
catch probable auth error and enables retry
test for probable auth error has been added as well.
> catch probable auth error and enables retry

- tasks.py
> [MAINTENANCE] Add aliases for invoke pre-release and release

- README.md
Some small edits to the release / pre-release sections of the readme
> Slight clarifications

- Dockerfile
- pyproject.toml
- Update python version `3.10.12` -> `3.10.13` 
- [Proposed change from 2024-04-17](https://greatexpectations.atlassian.net/wiki/x/B4CcP) to address vulnerabilities.
> Upgrade Docker image to Python `3.10.13`

- Dockerfile
- pyproject.toml
> Revert upgrade python version in Docker image

- .github/workflows/ci.yaml
- Dockerfile
- tasks.py
Install `python3-dev` to fix `python 3.10.13` container
Add ci check to run `invoke docker` to ensure docker container builds on every PR
> Fix Python 3.10.13 container

- README.md
add dependabot guidelines to readme
open to suggestions here, please let me know if anything should be added.
> add dependabot guidelines to readme

- pyproject.toml
- Cut a release of the agent.
- Manually ran through test cases:
- Run Validation
- Run Checkpoint
- Generate Metrics
> Release 20240423.0

- README.md
Updating README as discussed in https://github.com/great-expectations/cloud/pull/216#pullrequestreview-2018018976
> update readme for clarity re: pyproject.toml updates

- .github/workflows/ci.yaml
- great_expectations_cloud/agent/agent.py
- pyproject.toml
Issue: getting error during CI version bump:
Fix (hopefully): adding user name/email to git config for CI version bump commit action.
> Add user email and name to config for ci bump commit

- pyproject.toml
Changes in this PR were made by running `invoke-release` for today's release.
> 20240502.0 release

- Dockerfile
- pyproject.toml
Bump the python version to avoid some vulnerabilities.
> Bump base image python version

- poetry.lock
- pyproject.toml
https://github.com/great-expectations/great_expectations/releases/tag/0.18.14
> `great_expectations` - `0.18.14`

- pyproject.toml
Release the agent with latest changes.
> Release 20240605.0

- poetry.lock
- pyproject.toml
Bump the `great_expectations` version to `0.18.16`
> great-expectations 0.18.16

- great_expectations_cloud/agent/actions/data_assistants/utils.py
- poetry.lock
- pyproject.toml
Update min version of `great_expectations`
- https://github.com/great-expectations/great_expectations/releases/tag/0.18.19
> `great_expectations` `0.18.19`

- pyproject.toml
Includes changes from `great_expectations` [0.18.19](https://github.com/great-expectations/great_expectations/releases/tag/0.18.19)
> July 16 2024 Release

- pyproject.toml
- all dependabot PRs merged (except for the snowflake-sqlalchemy one we were waiting to merge)
- smoketesting complete and ✅
> July 23 2024 release

- poetry.lock
- pyproject.toml
Add [databricks-sql-python](https://github.com/databricks/databricks-sql-python) as a direct dependency
> Databricks SQL dependency

- great_expectations_cloud/agent/agent.py
- pyproject.toml
Yep. That was a mistake. Restoring the function signatures.
Also found a session that wasn't getting closed.
> restore function signatures

- great_expectations_cloud/logging/logging_cfg.py
Reduce level of pika logs, causing many many logs in infra
> reduce pika logs

- pyproject.toml
for logging change in https://github.com/great-expectations/cloud/pull/388
> bump dev version

- pyproject.toml
- No GX Core updates
- E2E test success
> release 20240812.0

- pyproject.toml
- Releasing a second logging fix for fstrings: https://github.com/great-expectations/cloud/pull/391
> release 20240812.1

- .github/workflows/ci.yaml
- codecov.yml
Enable support for reporting test results in Codecov.
This can help us identify flaky and poor performing tests.
> Codecov Test Results

- pyproject.toml
Tested on a new [dev-zelda-pod datasource + asset](https://app.dev.greatexpectations.io/organizations/dev-zelda-pod/data-assets/0ada54b2-a409-4031-bf6b-499a0033621a/validations/expectation-suites/ef6e1fd1-9740-47c4-99f2-3a8b94ff0d73/results) (first validation was scheduled, second run manually).
> Release 20240820.0

- great_expectations_cloud/agent/models.py
- pyproject.toml
For the upcoming Dynamic Parameters work. This is a placeholder, the action will be added in a subsequent PR.
If someone creates this event before the action is added, the agent will raise a `NoVersionImplementationError`.
> Add RunWindowCheckpointEvent

- poetry.lock
- pyproject.toml
> Poetry Lock update

- README.md
Link to the supported deployment methods.
> Update README to point to GX Docs

- pyproject.toml
Ensure the revert gets tagged appropriately
> set next stable version

- pyproject.toml
- Bump Ruff versions
- Bump pydantic versions
> release 20241001

- README.md
- great_expectations_cloud/agent/agent.py
- pyproject.toml
We are printing stray print statements into logs
> Remove Extra print statements from logs

- great_expectations_cloud/agent/agent.py
- pyproject.toml
need to see what this event looks like when in flight
> debug - add event payload to log context

- great_expectations_cloud/agent/actions/__init__.py
- pyproject.toml
Make `GenerateSchemaChangeExpectationsAction` an available action.
> enable generate_schema_change_expectations_request

- .github/workflows/ci.yaml
- .github/workflows/containerize-agent.yaml
- pyproject.toml
Temporarily pin poetry and kill the cached version
> Temporarily pin poetry in all workflows

- pyproject.toml
Release Agent with GX Core 1.3.5
> Release Agent with GX Core 1.3.5

- great_expectations_cloud/agent/actions/generate_data_quality_check_expectations_action.py
- great_expectations_cloud/agent/utils.py
- pyproject.toml
- tests/agent/test_utils.py
- tests/integration/actions/test_generate_data_quality_check_expectations.py
Generates completeness expectations for each column on a given asset
Types of completeness expectations generated:
- if 100% of rows of a given column are null: `ExpectColumnValuesToBeNull(column=column, mostly=1)`
- if 100% of rows are not null: `ExpectColumnValuesToNotBeNull(column=column, mostly=1)`
- else: `ExpectColumnValuesToBeNull(windows=windows, column=column, mostly=parameter)`
https://github.com/user-attachments/assets/e3bcb1e7-e952-49a1-ba39-0fef6dd836c9
> add completeness expectations

- poetry.lock
- pyproject.toml
> Upgrade GX Core

- pyproject.toml
> Agent release

- great_expectations_cloud/agent/actions/generate_data_quality_check_expectations_action.py
- pyproject.toml
- tests/agent/actions/test_generate_data_quality_check_expectations_action.py
- tests/integration/actions/test_generate_data_quality_check_expectations.py
- Make those cases not dynamic
- Add tests for these edge cases
> Non-dynamic parameter Expectations for 0% and 100% null cases

- pyproject.toml
We didn't capture the newest OSS release when we released the agent last week.
> GX Agent release

- pyproject.toml
This release includes SQL Server drivers. Note that it does not yet guarantee full SQL Server support.
> Release 20250825.0

- pyproject.toml
Smoke tested in Internal Peach Pod Org in production
> Release 20250828.0

- great_expectations_cloud/agent/actions/utils.py
- pyproject.toml
- tests/agent/actions/test_draft_datasource_config.py
- tests/agent/actions/test_utils.py
> Properly quote asset names when listing them

- pyproject.toml
Smoke tested in Peach org in prod
> Release 20250915.0
